from Models.models.model_interface import InputData

""" This file serves as a quickfix for some data issues that are still unresolved """

InputData2Keys = {
    InputData.PRICE_DATA: [
        "1. open",
        "2. high",
        "3. low",
        "4. close",
        "5. volume"
    ],
    InputData.TECHNICAL_INDICATORS: [
        "sma",
        "ema",
        "macd",
        "rsi",
        "cci",
        "adx",
        "stoch",
        "aroon",
        "bbands",
        "ad",
        "obv"
    ],
    InputData.EARNINGS: [
        "fiscalDateEnding",
        "reportedDate",
        "reportedEPS",
        "estimatedEPS",
        "surprise",
        "surprisePercentage"
    ],
    InputData.CASH_FLOW: [
        "fiscalDateEnding",
        "reportedCurrency",
        "operatingCashflow",
        "paymentsForOperatingActivities",
        "proceedsFromOperatingActivities",
        "changeInOperatingLiabilities",
        "changeInOperatingAssets",
        "depreciationDepletionAndAmortization",
        "capitalExpenditures",
        "changeInReceivables",
        "changeInInventory",
        "profitLoss",
        "cashflowFromInvestment",
        "cashflowFromFinancing",
        "proceedsFromRepaymentsOfShortTermDebt",
        "paymentsForRepurchaseOfCommonStock",
        "paymentsForRepurchaseOfEquity",
        "paymentsForRepurchaseOfPreferredStock",
        "dividendPayout",
        "dividendPayoutCommonStock",
        "dividendPayoutPreferredStock",
        "proceedsFromIssuanceOfCommonStock",
        "proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet",
        "proceedsFromIssuanceOfPreferredStock",
        "proceedsFromRepurchaseOfEquity",
        "proceedsFromSaleOfTreasuryStock",
        "changeInCashAndCashEquivalents",
        "changeInExchangeRate",
        "netIncome"
    ],
    InputData.INCOME_STATEMENT: [
        "fiscalDateEnding",
        "reportedCurrency",
        "grossProfit",
        "totalRevenue",
        "costOfRevenue",
        "costofGoodsAndServicesSold",
        "operatingIncome",
        "sellingGeneralAndAdministrative",
        "researchAndDevelopment",
        "operatingExpenses",
        "investmentIncomeNet",
        "netInterestIncome",
        "interestIncome",
        "interestExpense",
        "nonInterestIncome",
        "otherNonOperatingIncome",
        "depreciation",
        "depreciationAndAmortization",
        "incomeBeforeTax",
        "incomeTaxExpense",
        "interestAndDebtExpense",
        "netIncomeFromContinuingOperations",
        "comprehensiveIncomeNetOfTax",
        "ebit",
        "ebitda",
        "netIncome"
    ],
    InputData.BALANCE_SHEET: [
        "fiscalDateEnding",
        "reportedCurrency",
        "totalAssets",
        "totalCurrentAssets",
        "cashAndCashEquivalentsAtCarryingValue",
        "cashAndShortTermInvestments",
        "inventory",
        "currentNetReceivables",
        "totalNonCurrentAssets",
        "propertyPlantEquipment",
        "accumulatedDepreciationAmortizationPPE",
        "intangibleAssets",
        "intangibleAssetsExcludingGoodwill",
        "goodwill",
        "investments",
        "longTermInvestments",
        "shortTermInvestments",
        "otherCurrentAssets",
        "otherNonCurrrentAssets",
        "totalLiabilities",
        "totalCurrentLiabilities",
        "currentAccountsPayable",
        "deferredRevenue",
        "currentDebt",
        "shortTermDebt",
        "totalNonCurrentLiabilities",
        "capitalLeaseObligations",
        "longTermDebt",
        "currentLongTermDebt",
        "longTermDebtNoncurrent",
        "shortLongTermDebtTotal",
        "otherCurrentLiabilities",
        "otherNonCurrentLiabilities",
        "totalShareholderEquity",
        "treasuryStock",
        "retainedEarnings",
        "commonStock",
        "commonStockSharesOutstanding"
    ]
}

DatabaseKeySpecification = {
    "1. open": {"clean_name": "open", "type": float, "group": [InputData.PRICE_DATA]},
    "2. high": {"clean_name": "high", "type": float, "group": [InputData.PRICE_DATA]},
    "3. low": {"clean_name": "low", "type": float, "group": [InputData.PRICE_DATA]},
    "4. close": {"clean_name": "close", "type": float, "group": [InputData.PRICE_DATA]},
    "5. volume": {"clean_name": "volume", "type": float, "group": [InputData.PRICE_DATA]},
    "SMA": {"clean_name": "sma", "type": float, "group": [InputData.TECHNICAL_INDICATORS]},
    "EMA": {"clean_name": "ema", "type": float, "group": [InputData.TECHNICAL_INDICATORS]},
    "MACD": {"clean_name": "macd", "type": float, "group": [InputData.TECHNICAL_INDICATORS]},
    "MACD_Hist": {"clean_name": "macd_hist", "type": float, "group": [InputData.TECHNICAL_INDICATORS]},
    "MACD_Signal": {"clean_name": "macd_signal", "type": float, "group": [InputData.TECHNICAL_INDICATORS]},
    "RSI": {"clean_name": "rsi", "type": float, "group": [InputData.TECHNICAL_INDICATORS]},
    "CCI": {"clean_name": "cci", "type": float, "group": [InputData.TECHNICAL_INDICATORS]},
    "ADX": {"clean_name": "adx", "type": float, "group": [InputData.TECHNICAL_INDICATORS]},
    "SlowD": {"clean_name": "stoch_slowd", "type": float, "group": [InputData.TECHNICAL_INDICATORS]},
    "SlowK": {"clean_name": "stoch_slowk", "type": float, "group": [InputData.TECHNICAL_INDICATORS]},
    "Arron Up": {"clean_name": "aroon_up", "type": float, "group": [InputData.TECHNICAL_INDICATORS]},
    "Aroon Down": {"clean_name": "aroon_down", "type": float, "group": [InputData.TECHNICAL_INDICATORS]},
    "Real Upper Band": {"clean_name": "bbands_real_upper", "type": float, "group": [InputData.TECHNICAL_INDICATORS]},
    "Real Middle Band": {"clean_name": "bbands_real_middle", "type": float, "group": [InputData.TECHNICAL_INDICATORS]},
    "Real Lower Band": {"clean_name": "bbands_real_lower", "type": float, "group": [InputData.TECHNICAL_INDICATORS]},
    "Chaikin A/D": {"clean_name": "ad", "type": float, "group": [InputData.TECHNICAL_INDICATORS]},
    "OBV": {"clean_name": "obv", "type": float, "group": [InputData.TECHNICAL_INDICATORS]},
    "fiscalDateEnding": {"clean_name": "fiscalDateEnding", "type": str, "group": [InputData.EARNINGS, InputData.CASH_FLOW, InputData.INCOME_STATEMENT, InputData.BALANCE_SHEET]},
    "reportedDate": {"clean_name": "reportedDate", "type": str, "group": [InputData.EARNINGS]},
    "reportedEPS": {"clean_name": "reportedEPS", "type": float, "group": [InputData.EARNINGS]},
    "estimatedEPS": {"clean_name": "estimatedEPS", "type": float, "group": [InputData.EARNINGS]},
    "surprise": {"clean_name": "surprise", "type": float, "group": [InputData.EARNINGS]},
    "surprisePercentage": {"clean_name": "surprisePercentage", "type": float, "group": [InputData.EARNINGS]},
    "reportedCurrency": {"clean_name": "reportedCurrency", "type": str, "group": [InputData.CASH_FLOW, InputData.INCOME_STATEMENT, InputData.BALANCE_SHEET]},
    "operatingCashflow": {"clean_name": "operatingCashFlow", "type": float, "group": [InputData.CASH_FLOW]},
    "paymentsForOperatingActivities": {"clean_name": "paymentsForOperatingActivities", "type": float, "group": [InputData.CASH_FLOW]},
    "proceedsFromOperatingActivities": {"clean_name": "proceedsFromOperatingActivities", "type": float, "group": [InputData.CASH_FLOW]},
    "changeInOperatingLiabilities": {"clean_name": "changeInOperatingLiabilities", "type": float, "group": [InputData.CASH_FLOW]},
    "changeInOperatingAssets": {"clean_name": "changeInOperatingAssets", "type": float, "group": [InputData.CASH_FLOW]},
    "depreciationDepletionAndAmortization": {"clean_name": "depreciationDepletionAndAmortization", "type": float, "group": [InputData.CASH_FLOW]},
    "capitalExpenditures": {"clean_name": "capitalExpenditures", "type": float, "group": [InputData.CASH_FLOW]},
    "changeInReceivables": {"clean_name": "changeInReceivables", "type": float, "group": [InputData.CASH_FLOW]},
    "changeInInventory": {"clean_name": "changeInInventory", "type": float, "group": [InputData.CASH_FLOW]},
    "profitLoss": {"clean_name": "profitLoss", "type": float, "group": [InputData.CASH_FLOW]},
    "cashflowFromInvestment": {"clean_name": "cashFlowFromInvestment", "type": float, "group": [InputData.CASH_FLOW]},
    "cashflowFromFinancing": {"clean_name": "cashFlowFromFinancing", "type": float, "group": [InputData.CASH_FLOW]},
    "proceedsFromRepaymentsOfShortTermDebt": {"clean_name": "proceedsFromRepaymentsOfShortTermDebt", "type": float, "group": [InputData.CASH_FLOW]},
    "paymentsForRepurchaseOfCommonStock": {"clean_name": "paymentsForRepurchaseOfCommonStock", "type": float, "group": [InputData.CASH_FLOW]},
    "paymentsForRepurchaseOfEquity": {"clean_name": "paymentsForRepurchaseOfEquity", "type": float, "group": [InputData.CASH_FLOW]},
    "paymentsForRepurchaseOfPreferredStock": {"clean_name": "paymentsForRepurchaseOfPreferredStock", "type": float, "group": [InputData.CASH_FLOW]},
    "dividendPayout": {"clean_name": "dividendPayout", "type": float, "group": [InputData.CASH_FLOW]},
    "dividendPayoutCommonStock": {"clean_name": "dividendPayoutCommonStock", "type": float, "group": [InputData.CASH_FLOW]},
    "dividendPayoutPreferredStock": {"clean_name": "dividendPayoutPreferredStock", "type": float, "group": [InputData.CASH_FLOW]},
    "proceedsFromIssuanceOfCommonStock": {"clean_name": "proceedsFromIssuanceOfCommonStock", "type": float, "group": [InputData.CASH_FLOW]},
    "proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet": { "clean_name": "proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet", "type": float, "group": [InputData.CASH_FLOW]},
    "proceedsFromIssuanceOfPreferredStock": {"clean_name": "proceedsFromIssuanceOfPreferredStock", "type": float, "group": [InputData.CASH_FLOW]},
    "proceedsFromRepurchaseOfEquity": {"clean_name": "proceedsFromRepurchaseOfEquity", "type": float, "group": [InputData.CASH_FLOW]},
    "proceedsFromSaleOfTreasuryStock": {"clean_name": "proceedsFromSaleOfTreasuryStock", "type": float, "group": [InputData.CASH_FLOW]},
    "changeInCashAndCashEquivalents": {"clean_name": "changeInCashAndCashEquivalents", "type": float, "group": [InputData.CASH_FLOW]},
    "changeInExchangeRate": {"clean_name": "changeInExchangeRate", "type": float, "group": [InputData.CASH_FLOW]},
    "netIncome": {"clean_name": "netIncome", "type": float, "group": [InputData.CASH_FLOW, InputData.INCOME_STATEMENT]},
    "grossProfit": {"clean_name": "grossProfit", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "totalRevenue": {"clean_name": "totalRevenue", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "costOfRevenue": {"clean_name": "costOfRevenue", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "costofGoodsAndServicesSold": {"clean_name": "costOfGoodsAndServicesSold", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "operatingIncome": {"clean_name": "operatingIncome", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "sellingGeneralAndAdministrative": {"clean_name": "sellingGeneralAndAdministrative", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "researchAndDevelopment": {"clean_name": "researchAndDevelopment", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "operatingExpenses": {"clean_name": "operatingExpenses", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "investmentIncomeNet": {"clean_name": "investmentIncomeNet", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "netInterestIncome": {"clean_name": "netInterestIncome", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "interestIncome": {"clean_name": "interestIncome", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "interestExpense": {"clean_name": "interestExpense", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "nonInterestIncome": {"clean_name": "nonInterestIncome", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "otherNonOperatingIncome": {"clean_name": "otherNonOperatingIncome", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "depreciation": {"clean_name": "depreciation", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "depreciationAndAmortization": {"clean_name": "depreciationAndAmortization", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "incomeBeforeTax": {"clean_name": "incomeBeforeTax", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "incomeTaxExpense": {"clean_name": "incomeTaxExpense", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "interestAndDebtExpense": {"clean_name": "interestAndDebtExpense", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "netIncomeFromContinuingOperations": {"clean_name": "netIncomeFromContinuingOperations", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "comprehensiveIncomeNetOfTax": {"clean_name": "comprehensiveIncomeNetOfTax", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "ebit": {"clean_name": "ebit", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "ebitda": {"clean_name": "ebitda", "type": float, "group": [InputData.INCOME_STATEMENT]},
    "totalAssets": {"clean_name": "totalAssets", "type": float, "group": [InputData.BALANCE_SHEET]},
    "totalCurrentAssets": {"clean_name": "totalCurrentAssets", "type": float, "group": [InputData.BALANCE_SHEET]},
    "cashAndCashEquivalentsAtCarryingValue": {"clean_name": "cashAndCashEquivalentsAtCarryingValue", "type": float, "group": [InputData.BALANCE_SHEET]},
    "cashAndShortTermInvestments": {"clean_name": "cashAndShortTermInvestments", "type": float, "group": [InputData.BALANCE_SHEET]},
    "inventory": {"clean_name": "inventory", "type": float, "group": [InputData.BALANCE_SHEET]},
    "currentNetReceivables": {"clean_name": "currentNetReceivables", "type": float, "group": [InputData.BALANCE_SHEET]},
    "totalNonCurrentAssets": {"clean_name": "totalNonCurrentAssets", "type": float, "group": [InputData.BALANCE_SHEET]},
    "propertyPlantEquipment": {"clean_name": "propertyPlantEquipment", "type": float, "group": [InputData.BALANCE_SHEET]},
    "accumulatedDepreciationAmortizationPPE": {"clean_name": "accumulatedDepreciationAmortizationPPE", "type": float, "group": [InputData.BALANCE_SHEET]},
    "intangibleAssets": {"clean_name": "intangibleAssets", "type": float, "group": [InputData.BALANCE_SHEET]},
    "intangibleAssetsExcludingGoodwill": {"clean_name": "intangibleAssetsExcludingGoodwill", "type": float, "group": [InputData.BALANCE_SHEET]},
    "goodwill": {"clean_name": "goodwill", "type": float, "group": [InputData.BALANCE_SHEET]},
    "investments": {"clean_name": "investments", "type": float, "group": [InputData.BALANCE_SHEET]},
    "longTermInvestments": {"clean_name": "longTermInvestments", "type": float, "group": [InputData.BALANCE_SHEET]},
    "shortTermInvestments": {"clean_name": "shortTermInvestments", "type": float, "group": [InputData.BALANCE_SHEET]},
    "otherCurrentAssets": {"clean_name": "otherCurrentAssets", "type": float, "group": [InputData.BALANCE_SHEET]},
    "otherNonCurrrentAssets": {"clean_name": "otherNonCurrentAssets", "type": float, "group": [InputData.BALANCE_SHEET]},
    "totalLiabilities": {"clean_name": "totalLiabilities", "type": float, "group": [InputData.BALANCE_SHEET]},
    "totalCurrentLiabilities": {"clean_name": "totalCurrentLiabilities", "type": float, "group": [InputData.BALANCE_SHEET]},
    "currentAccountsPayable": {"clean_name": "currentAccountsPayable", "type": float, "group": [InputData.BALANCE_SHEET]},
    "deferredRevenue": {"clean_name": "deferredRevenue", "type": float, "group": [InputData.BALANCE_SHEET]},
    "currentDebt": {"clean_name": "currentDebt", "type": float, "group": [InputData.BALANCE_SHEET]},
    "shortTermDebt": {"clean_name": "shortTermDebt", "type": float, "group": [InputData.BALANCE_SHEET]},
    "totalNonCurrentLiabilities": {"clean_name": "totalNonCurrentLiabilities", "type": float, "group": [InputData.BALANCE_SHEET]},
    "capitalLeaseObligations": {"clean_name": "capitalLeaseObligations", "type": float, "group": [InputData.BALANCE_SHEET]},
    "longTermDebt": {"clean_name": "longTermDebt", "type": float, "group": [InputData.BALANCE_SHEET]},
    "currentLongTermDebt": {"clean_name": "currentLongTermDebt", "type": float, "group": [InputData.BALANCE_SHEET]},
    "longTermDebtNoncurrent": {"clean_name": "longTermDebtNonCurrent", "type": float, "group": [InputData.BALANCE_SHEET]},
    "shortLongTermDebtTotal": {"clean_name": "shortLongTermDebtTotal", "type": float, "group": [InputData.BALANCE_SHEET]},
    "otherCurrentLiabilities": {"clean_name": "otherCurrentLiabilities", "type": float, "group": [InputData.BALANCE_SHEET]},
    "otherNonCurrentLiabilities": {"clean_name": "otherNonCurrentLiabilities", "type": float, "group": [InputData.BALANCE_SHEET]},
    "totalShareholderEquity": {"clean_name": "totalShareholderEquity", "type": float, "group": [InputData.BALANCE_SHEET]},
    "treasuryStock": {"clean_name": "treasuryStock", "type": float, "group": [InputData.BALANCE_SHEET]},
    "retainedEarnings": {"clean_name": "retainedEarnings", "type": float, "group": [InputData.BALANCE_SHEET]},
    "commonStock": {"clean_name": "commonStock", "type": float, "group": [InputData.BALANCE_SHEET]},
    "commonStockSharesOutstanding": {"clean_name": "commonStockSharesOutstanding", "type": float, "group": [InputData.BALANCE_SHEET]}
}
