class BalanceSheet:

    """class for representing fundamental data regarding balance_sheet"""

    def __init__(self, data):
        self.fiscalDateEnding = data["fiscalDateEnding"]
        self.reportedCurrency = data["reportedCurrency"]
        self.totalAssets = data["totalAssets"]
        self.totalCurrentAssets = data["totalCurrentAssets"]
        self.cashAndCashEquivalentsAtCarryingValue = data["cashAndCashEquivalentsAtCarryingValue"]
        self.cashAndShortTermInvestments = data["cashAndShortTermInvestments"]
        self.inventory = data["inventory"]
        self.currentNetReceivables = data["currentNetReceivables"]
        self.totalNonCurrentAssets = data["totalNonCurrentAssets"]
        self.propertyPlantEquipment = data["propertyPlantEquipment"]
        self.accumulatedDepreciationAmortizationPPE = data["accumulatedDepreciationAmortizationPPE"]
        self.intangibleAssets = data["intangibleAssets"]
        self.intangibleAssetsExcludingGoodwill = data["intangibleAssetsExcludingGoodwill"]
        self.goodwill = data["goodwill"]
        self.investments = data["investments"]
        self.longTermInvestments = data["longTermInvestments"]
        self.shortTermInvestments = data["shortTermInvestments"]
        self.otherCurrentAssets = data["otherCurrentAssets"]
        self.otherNonCurrrentAssets = data["otherNonCurrrentAssets"]
        self.totalLiabilities = data["totalLiabilities"]
        self.totalCurrentLiabilities = data["totalCurrentLiabilities"]
        self.currentAccountsPayable = data["currentAccountsPayable"]
        self.deferredRevenue = data["deferredRevenue"]
        self.currentDebt = data["currentDebt"]
        self.shortTermDebt = data["shortTermDebt"]
        self.totalNonCurrentLiabilities = data["totalNonCurrentLiabilities"]
        self.capitalLeaseObligations = data["capitalLeaseObligations"]
        self.longTermDebt = data["longTermDebt"]
        self.currentLongTermDebt = data["currentLongTermDebt"]
        self.longTermDebtNoncurrent = data["longTermDebtNoncurrent"]
        self.shortLongTermDebtTotal = data["shortLongTermDebtTotal"]
        self.otherCurrentLiabilities = data["otherCurrentLiabilities"]
        self.otherNonCurrentLiabilities = data["otherNonCurrentLiabilities"]
        self.totalShareholderEquity = data["totalShareholderEquity"]
        self.treasuryStock = data["treasuryStock"]
        self.retainedEarnings = data["retainedEarnings"]
        self.commonStock = data["commonStock"]
        self.commonStockSharesOutstanding = data["commonStockSharesOutstanding"]
