from dataclasses import dataclass, field


@dataclass
class BalanceSheet:
    """class for representing fundamental data regarding balance sheet"""

    fiscalDateEnding: str = field(default="")
    reportedCurrency: str = field(default="")
    totalAssets: float = field(default=.0)
    totalCurrentAssets: float = field(default=.0)
    cashAndCashEquivalentsAtCarryingValue: float = field(default=.0)
    cashAndShortTermInvestments: float = field(default=.0)
    inventory: float = field(default=.0)
    currentNetReceivables: float = field(default=.0)
    totalNonCurrentAssets: float = field(default=.0)
    propertyPlantEquipment: float = field(default=.0)
    accumulatedDepreciationAmortizationPPE: float = field(default=.0)
    intangibleAssets: float = field(default=.0)
    intangibleAssetsExcludingGoodwill: float = field(default=.0)
    goodwill: float = field(default=.0)
    investments: float = field(default=.0)
    longTermInvestments: float = field(default=.0)
    shortTermInvestments: float = field(default=.0)
    otherCurrentAssets: float = field(default=.0)
    otherNonCurrentAssets: float = field(default=.0)
    totalLiabilities: float = field(default=.0)
    totalCurrentLiabilities: float = field(default=.0)
    currentAccountsPayable: float = field(default=.0)
    deferredRevenue: float = field(default=.0)
    currentDebt: float = field(default=.0)
    shortTermDebt: float = field(default=.0)
    totalNonCurrentLiabilities: float = field(default=.0)
    capitalLeaseObligations: float = field(default=.0)
    longTermDebt: float = field(default=.0)
    currentLongTermDebt: float = field(default=.0)
    longTermDebtNonCurrent: float = field(default=.0)
    shortLongTermDebtTotal: float = field(default=.0)
    otherCurrentLiabilities: float = field(default=.0)
    otherNonCurrentLiabilities: float = field(default=.0)
    totalShareholderEquity: float = field(default=.0)
    treasuryStock: float = field(default=.0)
    retainedEarnings: float = field(default=.0)
    commonStock: float = field(default=.0)
    commonStockSharesOutstanding: float = field(default=.0)
