from dataclasses import dataclass, field


@dataclass(frozen=True)
class CompanyOverview:
    """class for representing fundamental data regarding company overview"""

    symbol: str = field(default=None)
    assetType: str = field(default=None)
    name: str = field(default=None)
    cik: float = field(default=None)
    exchange: str = field(default=None)
    currency: str = field(default=None)
    country: str = field(default=None)
    sector: str = field(default=None)
    industry: str = field(default=None)
    address: str = field(default=None)
    fiscalYearEnd: str = field(default=None)
    latestQuarter: str = field(default=None)
    marketCapitalization: float = field(default=None)
    ebitda: float = field(default=None)
    peRatio: float = field(default=None)
    pegRatio: float = field(default=None)
    bookValue: float = field(default=None)
    dividendPerShare: float = field(default=None)
    dividendYield: float = field(default=None)
    eps: float = field(default=None)
    revenuePerShareTTM: float = field(default=None)
    profitMargin: float = field(default=None)
    operatingMarginTTM: float = field(default=None)
    returnOnAssetsTTM: float = field(default=None)
    returnOnEquityTTM: float = field(default=None)
    revenueTTM: float = field(default=None)
    grossProfitTTM: float = field(default=None)
    dilutedEPSTTM: float = field(default=None)
    quarterlyEarningsGrowthYOY: float = field(default=None)
    quarterlyRevenueGrowthYOY: float = field(default=None)
    analystTargetPrice: float = field(default=None)
    trailingPE: float = field(default=None)
    forwardPE: float = field(default=None)
    priceToSalesRatioTTM: float = field(default=None)
    priceToBookRatio: float = field(default=None)
    evToRevenue: float = field(default=None)
    evToEBITDA: float = field(default=None)
    beta: float = field(default=None)
    weekHigh52: float = field(default=None)
    weekLow52: float = field(default=None)
    dayMovingAverage50: float = field(default=None)
    dayMovingAverage200: float = field(default=None)
    sharesOutstanding: float = field(default=None)
    sharesFloat: float = field(default=None)
    sharesShort: float = field(default=None)
    sharesShortPriorMonth: float = field(default=None)
    shortRatio: float = field(default=None)
    shortPercentOutstanding: float = field(default=None)
    shortPercentFloat: float = field(default=None)
    percentInsiders: float = field(default=None)
    percentInstitutions: float = field(default=None)
    forwardAnnualDividendRate: float = field(default=None)
    forwardAnnualDividendYield: float = field(default=None)
    payoutRatio: float = field(default=None)
    dividendDate: str = field(default=None)
    exDividendDate: str = field(default=None)
    lastSplitFactor: str = field(default=None)
    lastSplitDate: str = field(default=None)
