from dataclasses import dataclass, field


@dataclass
class CompanyOverview:
    """class for representing fundamental data regarding company overview"""

    symbol: str = field(default="")
    assetType: str = field(default="")
    name: str = field(default="")
    cik: float = field(default=.0)
    exchange: str = field(default="")
    currency: str = field(default="")
    country: str = field(default="")
    sector: str = field(default="")
    industry: str = field(default="")
    address: str = field(default="")
    fiscalYearEnd: str = field(default="")
    latestQuarter: str = field(default="")
    marketCapitalization: float = field(default=.0)
    ebitda: float = field(default=.0)
    peRatio: float = field(default=.0)
    pegRatio: float = field(default=.0)
    bookValue: float = field(default=.0)
    dividendPerShare: float = field(default=.0)
    dividendYield: float = field(default=.0)
    eps: float = field(default=.0)
    revenuePerShareTTM: float = field(default=.0)
    profitMargin: float = field(default=.0)
    operatingMarginTTM: float = field(default=.0)
    returnOnAssetsTTM: float = field(default=.0)
    returnOnEquityTTM: float = field(default=.0)
    revenueTTM: float = field(default=.0)
    grossProfitTTM: float = field(default=.0)
    dilutedEPSTTM: float = field(default=.0)
    quarterlyEarningsGrowthYOY: float = field(default=.0)
    quarterlyRevenueGrowthYOY: float = field(default=.0)
    analystTargetPrice: float = field(default=.0)
    trailingPE: float = field(default=.0)
    forwardPE: float = field(default=.0)
    priceToSalesRatioTTM: float = field(default=.0)
    priceToBookRatio: float = field(default=.0)
    evToRevenue: float = field(default=.0)
    evToEBITDA: float = field(default=.0)
    beta: float = field(default=.0)
    weekHigh52: float = field(default=.0)
    weekLow52: float = field(default=.0)
    dayMovingAverage50: float = field(default=.0)
    dayMovingAverage200: float = field(default=.0)
    sharesOutstanding: float = field(default=.0)
    sharesFloat: float = field(default=.0)
    sharesShort: float = field(default=.0)
    sharesShortPriorMonth: float = field(default=.0)
    shortRatio: float = field(default=.0)
    shortPercentOutstanding: float = field(default=.0)
    shortPercentFloat: float = field(default=.0)
    percentInsiders: float = field(default=.0)
    percentInstitutions: float = field(default=.0)
    forwardAnnualDividendRate: float = field(default=.0)
    forwardAnnualDividendYield: float = field(default=.0)
    payoutRatio: float = field(default=.0)
    dividendDate: str = field(default="")
    exDividendDate: str = field(default="")
    lastSplitFactor: str = field(default="")
    lastSplitDate: str = field(default="")
